analytics: {}
color:
  brandColors:
    - '#D0E0C8'
    - '#05487F'
    - '#A89050'
    - '#58B0F8'
    - '#90C8E0'
  brandStrength: 0.847973
  lightness: 0.313848
  rhythmicContrast: 0.067743
  saturation: 0.06617
cta: {}
layout_spectrum: 0.398648
name: Project-E
opengraph: {}
purpose: []
typography_spectrum: 0.0918
