name: Project-E
favicon: null
layout_spectrum: 0.8234677128493786
typography_spectrum: 0.10445069265551865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7788805370219052
  lightness: 0.31384803890250623
  saturation: 0.06617086636833847
  rhythmicContrast: 0.06774355284869671
purpose: []
